export default {
    DISCOVER_REQUEST: 'DISCOVER_REQUEST',
    DISCOVER_SUCCESS: 'DISCOVER_SUCCESS',
    DISCOVER_FAILURE: 'DISCOVER_FAILURE',

    SEARCH_REQUEST: 'SEARCH_REQUEST',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
    SEARCH_FAILURE: 'SEARCH_FAILURE',

    MOVIE_REQUEST: 'MOVIE_REQUEST',
    MOVIE_SUCCESS: 'MOVIE_SUCCESS',
    MOVIE_FAILURE: 'MOVIE_FAILURE',
}
