export default {
    DISCOVER_REQUEST: 'DISCOVER_REQUEST',
    DISCOVER_SUCCESS: 'DISCOVER_SUCCESS',
    DISCOVER_FAILURE: 'DISCOVER_FAILURE',

    SEARCH_REQUEST: 'SEARCH_REQUEST',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
    SEARCH_FAILURE: 'SEARCH_FAILURE',

    FETCH_MOVIE_REQUEST: 'FETCH_MOVIE_REQUEST',
    FETCH_MOVIE_SUCCESS: 'FETCH_MOVIE_SUCCESS',
    FETCH_MOVIE_FAILURE: 'FETCH_MOVIE_FAILURE',
}
