export { default as Input } from './input/input'
export { default as Jumbotron } from './jumbotron/jumbotron'
export { default as Loading } from './loading/loading'
export { default as Page } from './page/page'
export { default as Poster } from './poster/poster'
